import Head from "next/head";
import IntroMe from "../components/IntroMe";
import Navbar from "../components/Navbar";
import { useState } from "react";
import Footer from "../components/Footer";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Denny Raymond Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10  md:px-20 lg:40">
        <section className="min-h-screen ">
          <Navbar Props={{ darkMode }} />
          <IntroMe />
        </section>
        <Footer />
      </main>
    </div>
  );
}
